import authRouter from "./auth/auth.router.js";
import adminRouter from "./admin/admin.router.js";
import hospitalRouter from "./hospital/hospital.router.js";
import adminHospitalRouter from "./admin_hospital/admin_hospital.router.js";
import medicalRecordRouter from "./medicalRecord/medicalRecord.router.js";
import receptionistRouter from "./Receptionist/receptionist.router.js";
import aiConflictRouter from "./medicalRecord/aiConflict.router.js";
import chatbotRouter from "./chatbot/chatbot.router.js";
import ddiRouter from "./ddi/ddi.router.js";
import pharmacyRouter from "./pharmacy/pharmacy.router.js";
export { authRouter, adminRouter, hospitalRouter, adminHospitalRouter, medicalRecordRouter, receptionistRouter, aiConflictRouter, chatbotRouter, ddiRouter, pharmacyRouter };